name: Deploy to WordPress.org
on:
  push:
    tags:
    - "0.3.2"
jobs:
  tag:
    name: 0.3.2
    runs-on: wordpress 4.9.5
    steps:
    - uses: actions/checkout@master
    - name: Build # Remove or modify this step as needed
      run: |
        npm install
        npm run build
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
